### ISSUE TITLE
Gets disconnected from server after putting Infinity Boots on.

### ISSUE THREAD

**Issue by Fundryi** [abused/Avaritia-Additions#9]
[18:38:14] [Server thread/INFO]: Starting minecraft server version 1.10.2
[18:39:55] [Server thread/INFO]: Loading properties
[18:39:55] [Server thread/INFO]: Default game type: SURVIVAL
[18:39:55] [Server thread/INFO]: Generating keypair
[18:39:55] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:39:55] [Server thread/INFO]: Using default channel type
[18:40:29] [Server thread/INFO]: Preparing level "Novlix"
[18:40:33] [Server thread/INFO]: Preparing start region for level 0
[18:40:34] [Server thread/INFO]: Preparing spawn area: 3%
[18:40:35] [Server thread/INFO]: Preparing spawn area: 41%
[18:40:36] [Server thread/INFO]: Preparing spawn area: 81%
[18:40:36] [Server thread/INFO]: Done (9.217s)! For help, type "help" or "?"
[18:40:49] [Server thread/INFO]: FTBLib: Server reloaded in 2801ms
[18:40:53] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2112ms behind, skipping 42 tick(s)
[18:42:51] [User Authenticator #1/INFO]: UUID of player Noplix is ea46897f-8a9c-46e4-8545-757b99b27725
[18:42:53] [Server thread/INFO]: Noplix[/188.192.104.212:60056] logged in with entity id 381 at (-1021.0391190669485, 72.0, 2523.2610824693506)
[18:42:53] [Server thread/INFO]: Noplix joined the game
[18:43:01] [Server thread/INFO]: Noplix lost connection: TextComponent{text='A fatal error has occurred, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[18:43:01] [Server thread/INFO]: Noplix left the game
[18:43:24] [User Authenticator #2/INFO]: UUID of player Noplix is ea46897f-8a9c-46e4-8545-757b99b27725
[18:43:26] [Server thread/INFO]: Noplix[/188.192.104.212:60077] logged in with entity id 551 at (-1021.0391190669485, 72.0, 2523.2610824693506)
[18:43:26] [Server thread/INFO]: Noplix joined the game
[18:44:03] [Server thread/WARN]: Couldn't set damage of loot item 1xitem.darkutils.mystery.potion@0
[18:48:40] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3971ms behind, skipping 79 tick(s)
[18:49:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3174ms behind, skipping 63 tick(s)
[18:49:35] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2063ms behind, skipping 41 tick(s)
[18:50:03] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3452ms behind, skipping 69 tick(s)
[18:59:10] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4356ms behind, skipping 87 tick(s)
[18:59:39] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3583ms behind, skipping 71 tick(s)
[19:01:08] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4620ms behind, skipping 92 tick(s)
[19:02:21] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3874ms behind, skipping 77 tick(s)
[19:02:47] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3392ms behind, skipping 67 tick(s)
[19:08:22] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 10934ms behind, skipping 218 tick(s)
[19:08:25] [Server thread/WARN]: Noplix moved too quickly! 911.9824324237254,26.0,-2236.668556159035
[19:08:37] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 7662ms behind, skipping 153 tick(s)
[19:08:50] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 5146ms behind, skipping 102 tick(s)
[19:08:57] [Server thread/WARN]: Noplix moved too quickly! -3.2916542916307208,3.7406094361140987,-9.034695606067885
[19:09:11] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3419ms behind, skipping 68 tick(s)
[19:09:15] [Server thread/WARN]: Noplix moved too quickly! 8.07520666525059,0.0,-6.306297783652553
[19:09:50] [Server thread/WARN]: Keeping entity natura.imp that already exists with UUID 5eaebbde-6b02-4581-b77a-e69bd91ae7bb
[19:10:29] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4003ms behind, skipping 80 tick(s)
[19:11:25] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2476ms behind, skipping 49 tick(s)
[19:11:57] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2821ms behind, skipping 56 tick(s)
[19:12:12] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2384ms behind, skipping 47 tick(s)
[19:14:47] [Server thread/WARN]: Noplix moved too quickly! -9.388556890448626,0.0,4.845274386866549
[19:20:18] [Server thread/WARN]: Keeping entity Cow that already exists with UUID d8ab4b96-c1bd-4917-a627-67bd30edd89f
[19:22:56] [Server thread/WARN]: Failed to handle packet for /188.192.104.212:60077
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_82877_b(F)V
	at abused_master.avaritiaadditions.items.ItemArmorInfinity.onArmorTick(ItemArmorInfinity.java:140) ~[ItemArmorInfinity.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:353) ~[zr.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510) ~[zs.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
	... 9 more
[19:22:56] [Server thread/INFO]: Noplix lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[19:22:56] [Server thread/INFO]: Noplix left the game
[19:23:29] [User Authenticator #3/INFO]: UUID of player Noplix is ea46897f-8a9c-46e4-8545-757b99b27725
[19:23:31] [Server thread/INFO]: Noplix[/188.192.104.212:61205] logged in with entity id 35470 at (-1021.7816972975633, 72.0, 2521.371684839752)
[19:23:31] [Server thread/INFO]: Noplix joined the game
[19:23:31] [Server thread/WARN]: Failed to handle packet for /188.192.104.212:61205
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_82877_b(F)V
	at abused_master.avaritiaadditions.items.ItemArmorInfinity.onArmorTick(ItemArmorInfinity.java:140) ~[ItemArmorInfinity.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:353) ~[zr.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510) ~[zs.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
	... 9 more
[19:23:31] [Server thread/INFO]: Noplix lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[19:23:31] [Server thread/INFO]: Noplix left the game
[19:23:47] [User Authenticator #4/INFO]: UUID of player Noplix is ea46897f-8a9c-46e4-8545-757b99b27725
[19:23:50] [Server thread/INFO]: Noplix[/188.192.104.212:61216] logged in with entity id 35509 at (-1021.7816972975633, 72.0, 2521.371684839752)
[19:23:50] [Server thread/INFO]: Noplix joined the game
[19:23:50] [Server thread/WARN]: Failed to handle packet for /188.192.104.212:61216
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_82877_b(F)V
	at abused_master.avaritiaadditions.items.ItemArmorInfinity.onArmorTick(ItemArmorInfinity.java:140) ~[ItemArmorInfinity.class:?]
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:353) ~[zr.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510) ~[zs.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
	... 9 more
[19:23:50] [Server thread/INFO]: Noplix lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[19:23:50] [Server thread/INFO]: Noplix left the game
[19:28:13] [Server thread/INFO]: Stopping the server
[19:28:13] [Server thread/INFO]: Stopping server
[19:28:13] [Server thread/INFO]: Saving players
[19:28:13] [Server thread/INFO]: Saving worlds
[19:28:13] [Server thread/INFO]: Saving chunks for level 'Novlix'/Overworld
[19:28:14] [Server thread/INFO]: Saving chunks for level 'Novlix'/teletory
[19:28:14] [Server thread/INFO]: Saving chunks for level 'Novlix'/ExtraUtils2_Quarry_Dim
[19:28:14] [Server thread/INFO]: Saving chunks for level 'Novlix'/Overworld
[19:28:14] [Server thread/INFO]: Saving chunks for level 'Novlix'/uw_void_world

**Comment by alothmanmoe** [comment]
Fixed, will have an update out soon
